language: ruby
sudo: required
services:
  - docker
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - ruby-head
bundler_args: "--jobs=4 --retry=3"
cache:
  bundler: true

before_install:
  - gem update --system --no-document
  - gem install bundler --no-document

script:
  - bundle exec rake spec
notifications:
  email: false
  slack:
    secure: PcecHsVS6lw89K5PllW8xFlzu0d04p6lYfxlUZL0/yp9flAczElJME4RshSMSkbnu5e2Iw8KUA2xB1jkAzDo9qYoXveaKyjkFUOb1ZxYIVxzzfoDDwUNTMmSoyjZjvbeBUcpxxmxy6nXa3zS+gA2ohqWhS9WTTlTqyM5RriDjZ8=
matrix:
  allow_failures:
  - rvm: ruby-head
branches:
  only:
  - master
